apiVersion: v1
kind: Service
metadata:
  name: dentist-backend-service
spec:
  selector:
    app: dentist-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer